### ISSUE TITLE
add support to create clone out of lvm snapshot

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/lvm-localpv#13]

**Comment by murkylife** [comment]
I noticed that this project supports VolumeSnapshot. I would also like to be able to restore from the snapshots taken, i.e. creating a PVC from a snapshot.

example:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-restore
spec:
  dataSource:
    name: my-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: lvm
  accessModes:
    - ReadWriteOnce
```

My goal is to be able to use a backup tool like Kasten K10 to backup my PVCs to s3. For this it needs snapshot and restore functionality.
