### ISSUE TITLE
duplicate name label in lvm-node in chart

### ISSUE THREAD

**Issue by davidkarlsen** [openebs/lvm-localpv#131]
**What steps did you take and what happened:**
Apply install via flux, which uses kustomize for post-rendering, which is sensitive to duplicate yaml keys.

do:
```
helm template . > f.yaml
yamllint f.yaml
```
to showcase bug

```
# Source: openebs/charts/lvm-localpv/templates/lvm-node.yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: RELEASE-NAME-lvm-localpv-node
  labels:
    chart: lvm-localpv-0.7.1
    heritage: Helm
    openebs.io/version: "0.7.0"
    role: "openebs-lvm"
    name: "openebs-lvm-node"
    release: RELEASE-NAME
    openebs.io/component-name: "openebs-lvm-node"
spec:
  selector:
    matchLabels:
      name: "openebs-lvm-node"
      release: RELEASE-NAME
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        chart: lvm-localpv-0.7.1
        heritage: Helm
        openebs.io/version: "0.7.0"
        role: "openebs-lvm"
        name: "openebs-lvm-node" <-- HERE
        release: RELEASE-NAME
        openebs.io/component-name: "openebs-lvm-node"
        
        name: openebs-lvm-node <-- ALSO HERE

```
[A clear and concise description of what the bug is, and what commands you ran.]

**What did you expect to happen:**
No duplicate keys

**The output of the following commands will help us better understand what's going on**:
N/A

**Anything else you would like to add:**
N/A

**Environment:**
N/A
