### ISSUE TITLE
How can I create a static PVs?

### ISSUE THREAD

**Issue by cdevacc1** [openebs/lvm-localpv#224]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.]
This yaml file create pv but not lv on my disk
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-lvmpv
  csi:
    driver: local.csi.openebs.io
    volumeHandle: test-pv
```
**What did you expect to happen:**
```
$ sudo lvscan
ACTIVE  'dev/vg01/test-pv' [5.00 Gib] inherit
```

**Environment:**
- LVM Driver version: I don't know, maybe lastest.
- Kubernetes version (use `kubectl version`): 1.26.3
- Kubernetes installer & version: microk8s 1.26
- OS (e.g. from `/etc/os-release`): ubuntu server 22.04.02

**Comment by abhilashshetty04** [comment]
@cdevacc1 Thanks for reporting the issue. Did LVMVolume object got created? Can you share lvm volume controller log for this?

**Comment by Jean-Daniel** [comment]
Hello,

Im have the same issue. I'm trying to create a PV, but whatever I do, the controller ignore it, and does not create matching `LVMVolume` objet.

I tried to replicate a PV generated by the controller from a PVC like this:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: local.csi.openebs.io
    fsType: ext4
    volumeAttributes:
      openebs.io/cas-type: localpv-lvm
      openebs.io/volgroup: localpv
    volumeHandle: test-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: openebs.io/nodename
          operator: In
          values:
          - worker-2.cluster
  persistentVolumeReclaimPolicy: Delete
  storageClassName: localpv-delete
  volumeMode: Filesystem
```

When creating the PV, I only get this log from the controller:

```
I0331 14:39:28.757229       1 controller.go:1151] handleProtectionFinalizer Volume : &PersistentVolume{ObjectMeta:{test-pv    62065ecd-4ba4-4be7-a949-f21c49b2f30d 330330598 0 2024-03-31 14:39:28 +0000 UTC <nil> <nil> map[] map[] [] [kubernetes.io/pv-protection] [{kubectl Apply v1 2024-03-31 14:39:28 +0000 UTC FieldsV1 {"f:spec":{"f:accessModes":{},"f:capacity":{"f:storage":{}},"f:csi":{"f:driver":{},"f:fsType":{},"f:volumeAttributes":{"f:openebs.io/cas-type":{},"f:openebs.io/volgroup":{}},"f:volumeHandle":{}},"f:nodeAffinity":{"f:required":{}},"f:persistentVolumeReclaimPolicy":{},"f:storageClassName":{},"f:volumeMode":{}}} }]},Spec:PersistentVolumeSpec{Capacity:ResourceList{storage: {{5368709120 0} {<nil>} 5Gi BinarySI},},PersistentVolumeSource:PersistentVolumeSource{GCEPersistentDisk:nil,AWSElasticBlockStore:nil,HostPath:nil,Glusterfs:nil,NFS:nil,RBD:nil,ISCSI:nil,Cinder:nil,CephFS:nil,FC:nil,Flocker:nil,FlexVolume:nil,AzureFile:nil,VsphereVolume:nil,Quobyte:nil,AzureDisk:nil,PhotonPersistentDisk:nil,PortworxVolume:nil,ScaleIO:nil,Local:nil,StorageOS:nil,CSI:&CSIPersistentVolumeSource{Driver:local.csi.openebs.io,VolumeHandle:test-pv,ReadOnly:false,FSType:ext4,VolumeAttributes:map[string]string{openebs.io/cas-type: localpv-lvm,openebs.io/volgroup: localpv,},ControllerPublishSecretRef:nil,NodeStageSecretRef:nil,NodePublishSecretRef:nil,ControllerExpandSecretRef:nil,NodeExpandSecretRef:nil,},},AccessModes:[ReadWriteOnce],ClaimRef:nil,PersistentVolumeReclaimPolicy:Delete,StorageClassName:localpv-delete,MountOptions:[],VolumeMode:*Filesystem,NodeAffinity:&VolumeNodeAffinity{Required:&NodeSelector{NodeSelectorTerms:[]NodeSelectorTerm{NodeSelectorTerm{MatchExpressions:[]NodeSelectorRequirement{NodeSelectorRequirement{Key:openebs.io/nodename,Operator:In,Values:[worker-2.cluster],},},MatchFields:[]NodeSelectorRequirement{},},},},},},Status:PersistentVolumeStatus{Phase:Pending,Message:,Reason:,},}
I0331 14:39:28.766192       1 controller.go:1151] handleProtectionFinalizer Volume : &PersistentVolume{ObjectMeta:{test-pv    62065ecd-4ba4-4be7-a949-f21c49b2f30d 330330600 0 2024-03-31 14:39:28 +0000 UTC <nil> <nil> map[] map[] [] [kubernetes.io/pv-protection] [{kubectl Apply v1 2024-03-31 14:39:28 +0000 UTC FieldsV1 {"f:spec":{"f:accessModes":{},"f:capacity":{"f:storage":{}},"f:csi":{"f:driver":{},"f:fsType":{},"f:volumeAttributes":{"f:openebs.io/cas-type":{},"f:openebs.io/volgroup":{}},"f:volumeHandle":{}},"f:nodeAffinity":{"f:required":{}},"f:persistentVolumeReclaimPolicy":{},"f:storageClassName":{},"f:volumeMode":{}}} } {kube-controller-manager Update v1 2024-03-31 14:39:28 +0000 UTC FieldsV1 {"f:status":{"f:phase":{}}} status}]},Spec:PersistentVolumeSpec{Capacity:ResourceList{storage: {{5368709120 0} {<nil>} 5Gi BinarySI},},PersistentVolumeSource:PersistentVolumeSource{GCEPersistentDisk:nil,AWSElasticBlockStore:nil,HostPath:nil,Glusterfs:nil,NFS:nil,RBD:nil,ISCSI:nil,Cinder:nil,CephFS:nil,FC:nil,Flocker:nil,FlexVolume:nil,AzureFile:nil,VsphereVolume:nil,Quobyte:nil,AzureDisk:nil,PhotonPersistentDisk:nil,PortworxVolume:nil,ScaleIO:nil,Local:nil,StorageOS:nil,CSI:&CSIPersistentVolumeSource{Driver:local.csi.openebs.io,VolumeHandle:test-pv,ReadOnly:false,FSType:ext4,VolumeAttributes:map[string]string{openebs.io/cas-type: localpv-lvm,openebs.io/volgroup: localpv,},ControllerPublishSecretRef:nil,NodeStageSecretRef:nil,NodePublishSecretRef:nil,ControllerExpandSecretRef:nil,NodeExpandSecretRef:nil,},},AccessModes:[ReadWriteOnce],ClaimRef:nil,PersistentVolumeReclaimPolicy:Delete,StorageClassName:localpv-delete,MountOptions:[],VolumeMode:*Filesystem,NodeAffinity:&VolumeNodeAffinity{Required:&NodeSelector{NodeSelectorTerms:[]NodeSelectorTerm{NodeSelectorTerm{MatchExpressions:[]NodeSelectorRequirement{NodeSelectorRequirement{Key:openebs.io/nodename,Operator:In,Values:[worker-2.cluster],},},MatchFields:[]NodeSelectorRequirement{},},},},},},Status:PersistentVolumeStatus{Phase:Available,Message:,Reason:,},}
```

No LVMVolume created.
