### ISSUE TITLE
lvm-localpv + FC + PureStorage

### ISSUE THREAD

**Issue by metbog** [openebs/lvm-localpv#257]
Hi there,

We have a Kubernetes cluster (k8s) with BareMetal (BM) workers. These BM workers are connected via Fibre Channel (FC) to PureStorage FA. Our goal is to create a shared volume for our BM workers and use it with lvm-localpv.

PureStorage -> (BM1, BM2) -> /dev/mapper/sharevolume (attached to each BM worker via FC) -> PV -> VG1

Here is StorageClass:
```
allowVolumeExpansion: false
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - bm-worker1
    - bm-worker2
    - bm-worker3
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pure-lvm
parameters:
  storage: lvm
  volgroup: test-pure-volume
provisioner: local.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

One idea is to make it possible to reattach LVM to any of the BM workers because currently, it creates a Persistent Volume  bound to one worker (where it was originally created). This limitation prevents pods from starting on other workers.

Is it possible to achieve this? Perhaps there is already a solution available for this issue?
