### ISSUE TITLE
JSON Array fields problem in `StorageClass` Parameter

### ISSUE THREAD

**Issue by mhkarimi1383** [openebs/lvm-localpv#359]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.]

Apply an `StorageClass` with info below

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvmpv
parameters:
  storage: "lvm"
  volgroup: "lvmvg"
  mountOptions:
    - debug
  # formatOptions:
  #   - -N
  #   - "16400"
provisioner: local.csi.openebs.io
```

And getting

Error from server (BadRequest): error when creating "sc.yaml": StorageClass in version "v1" cannot be handled as a StorageClass: json: cannot unmarshal array into Go struct field StorageClass.parameters of type string

**What did you expect to happen:**

Docs examples work

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other [Pastebin](https://pastebin.com/) is fine.)

* `kubectl logs -f openebs-lvm-localpv-controller-7b6d6b4665-fk78q -n openebs -c openebs-lvm-plugin`
* `kubectl logs -f openebs-lvm-localpv-node-[xxxx] -n openebs -c openebs-lvm-plugin`
* `kubectl get pods -n openebs`
* `kubectl get lvmvol -A -o yaml`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- LVM Driver version: 1.7.0-develop (Local build)
- Kubernetes version (use `kubectl version`): 
```shell
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.7", GitCommit:"07a61d861519c45ef5c89bc22dda289328f29343", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.0", GitCommit:"9edcffcde5595e8a5b1a35f88c421764e575afce", GitTreeState:"clean", BuildDate:"2024-08-13T07:28:49Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/amd64"}
Kubecolor Version: 0.4.0
```
- Kubernetes installer & version: Minikube
- Cloud provider or hardware configuration: Minikube
- OS (e.g. from `/etc/os-release`): NixOS (Local)

**Comment by tiagolobocastro** [comment]
`StorageClass` is not an openebs construct.
But in this particular case, this is erroring out because `mountOptions` is not inside parameters, see https://kubernetes.io/docs/concepts/storage/storage-classes/

For your example, it should be:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvmpv
parameters:
  storage: "lvm"
  volgroup: "lvmvg"
mountOptions:
  - debug
  # formatOptions:
  #   - -N
  #   - "16400"
provisioner: local.csi.openebs.io
```
