### ISSUE TITLE
add support to create thin snapshots

### ISSUE THREAD

**Issue by pawanpraka1** [openebs/lvm-localpv#98]
By default we create thick snapshot for all kind of provisioned volumes. We need to add support for thin snapshot. We should create thin snapshots for thin volumes and thick snapshots for thick volumes.

So there are two scenarios here :

1. Snapshot class `snapsize` parameter
```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: lvmpv-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
parameters:
  snapsize: 50%
driver: local.csi.openebs.io
deletionPolicy: Delete
```

In this case whether volume is thin provisioned or thick provisioned, we should create a thick snapshot with size as snapsize mentioned in the snapshotclass.

2. Snapshot class does not have `snapsize` parameter
```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: lvmpv-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: local.csi.openebs.io
deletionPolicy: Delete
```
In this case, for thin volumes, we should create a thin snapshot and for thick volume, we should create a thick snapshot. While creating the thick snapshot for thick volumes, since snapsize parameter is not provided, driver should reserve size equal to the volume for snapshots.
